{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "algon.serviceAccountName" . }}
  labels:
    {{- include "algon.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: dev
  name: secret-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-writer-binding
  namespace: dev
roleRef: # points to my Role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-writer # name of role
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: algon # service account to bind to
  namespace: dev # ns of service account
  apiGroup: ""
